name: Code Quality Check

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Run Pylint analysis
      run: |
        pylint --disable=C0114,C0116 $(git ls-files '*.py')
        
    - name: Check code formatting
      run: |
        python -c "
        import os
        files = [f for f in os.listdir('.') if f.endswith('.py')]
        print(f'Found {len(files)} Python files')
        "
